// <auto-generated />
namespace ZavenDotNetInterview.App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Add_Column_LastUpdatedAt_In_Job : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_Column_LastUpdatedAt_In_Job));
        
        string IMigrationMetadata.Id
        {
            get { return "202101311652076_Add_Column_LastUpdatedAt_In_Job"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
